#include "test_data.hpp"
#include "test_functor_distance.hpp"
#include "test_functor_smoothness.hpp"
//#include "test_groundtruth.hpp"
#include "test_image_preprocessing.hpp"
#include "test_parameters.hpp"
#include "test_solver.hpp"
